# This dockerfile is only aimed to be used for testing the blocking filter

ARG TRACEABLE_GOAGENT_DISTRO_VERSION

FROM traceable_goagent_test:${TRACEABLE_GOAGENT_DISTRO_VERSION}

WORKDIR /usr/local/test

# We first copy these files to be able to cache the dependencies download
# and speed up the test container.
COPY go.mod go.mod
COPY go.sum go.sum

COPY . .

RUN go get ./...

RUN CGO_ENABLED=1 go test -count=1 -v -race -cover ./...
