trigger:
  name: Push_Prerelease
  identifier: Push_Prerelease
  enabled: true
  orgIdentifier: PROD
  projectIdentifier: Traceable
  pipelineIdentifier: goagent_src_distro_test
  source:
    type: Webhook
    spec:
      type: Harness
      spec:
        type: Push
        spec:
          repoName: goagent-src
          autoAbortPreviousExecutions: false
          payloadConditions:
            - key: targetBranch
              operator: Regex
              value: ^prerelease\/.+\..+$
  inputSetRefs:
    - Push_Branch_Input_Set
  pipelineBranchName: main
