service_name: grpc-server

reporting:
  endpoint: localhost:4317
  secure: false
  trace_reporter_type: OTLP

opa:
  enabled: false

debug_log: true

remote_config:
  enabled: true
  endpoint: localhost:5441
  poll_period_seconds: 30
