ARG DEBIAN_VERSION

FROM debian:${DEBIAN_VERSION}

RUN apt-get -qq update && apt-get -qq install -y wget git gcc

ARG GO_VERSION

RUN wget https://dl.google.com/go/go${GO_VERSION}.linux-amd64.tar.gz && \
    tar -xvf go${GO_VERSION}.linux-amd64.tar.gz && \
    mv go /usr/local

ENV GOROOT=/usr/local/go
ENV PATH=$GOPATH/bin:$GOROOT/bin:$PATH

# This fix resolves the warning
#
# /bin/ld: warning: libc.musl-x86_64.so.1, needed by filter/traceable/libs/libtraceable.so, 
# not found (try using -rpath or -rpath-link)
#
# See https://github.com/alexander-akhmetov/python-telegram/issues/3
RUN apt-get install -y musl-dev
RUN ln -s /usr/lib/x86_64-linux-musl/libc.so /lib/libc.musl-x86_64.so.1
