ARG CENTOS_VERSION

FROM centos:${CENTOS_VERSION}

RUN yum -y update && yum install -y wget gcc

ARG GO_VERSION

RUN wget https://dl.google.com/go/go${GO_VERSION}.linux-amd64.tar.gz && \
    tar -xvf go${GO_VERSION}.linux-amd64.tar.gz && \
    mv go /usr/local

ENV GOROOT=/usr/local/go
ENV PATH=$GOPATH/bin:$GOROOT/bin:$PATH

ARG BUILD_TAGS=""