# This dockerfile is only aimed to be used for testing the blocking filter

ARG TRACEABLE_GOAGENT_DISTRO_VERSION

FROM traceable_goagent_test_base:${TRACEABLE_GOAGENT_DISTRO_VERSION}

WORKDIR /go/src/github.com/Traceableai/goagent

COPY . .

# Go get expects the library to be present when retrieving the dependencies
RUN cp /usr/local/traceable/libtraceable.so .
RUN go get ./...

# Runs blocking package tests to make sure it works.
RUN CGO_ENABLED=1 go test -c ./filters/blocking
RUN ./blocking.test

WORKDIR /go/src/github.com/Traceableai/goagent/_tests

# Runs the test app to make sure blocking filter works as expected.
RUN cp /usr/local/traceable/libtraceable.so .
RUN go build -o test-app .
RUN ./test-app
