# This dockerfile is only aimed to be used for testing the blocking filter

ARG TRACEABLE_GOAGENT_DISTRO_VERSION

FROM traceable_goagent_test_base:${TRACEABLE_GOAGENT_DISTRO_VERSION}

WORKDIR ${GOPATH}/src/github.com/Traceableai/goagent

COPY go.mod go.mod
COPY go.sum go.sum

RUN go get ./...

COPY . .

WORKDIR ${GOPATH}/src/github.com/Traceableai/goagent/_tests

# Runs the test app to make sure blocking filter works as expected.
RUN if [ "${IS_ALPINE}" = "1" ]; then \
    CGO_ENABLED=1 go build --tags="traceable_filter alpine" -o test-app . ; \
    else \
    CGO_ENABLED=1 go build --tags="traceable_filter" -o test-app . ; \
    fi

# Makes sure libtraceable isn't present during the test.
RUN if [ -f "libtraceable.so" ]; then \
    echo "libtraceable shouldn't be present for this test." && \
    exit 1 ; \
    fi

RUN TA_LOG_LEVEL="debug" ./test-app
