# Copied from https://github.com/docker-library/golang/blob/4598bb8c77b4e162d2a1d14598d9d83a8e3750c2/1.13/alpine3.12/Dockerfile

ARG ALPINE_VERSION

FROM alpine:${ALPINE_VERSION}

ARG GO_VERSION

# We need to install go on beforehand before targeting an exact version
# see https://stackoverflow.com/a/36689186
RUN apk add --no-cache --virtual .build-deps bash build-base musl-dev libc-dev openssl go gcc
RUN wget -O go.tgz https://dl.google.com/go/go${GO_VERSION}.src.tar.gz 
RUN tar -C /usr/local -xzf go.tgz
RUN cd /usr/local/go/src/ && ./make.bash 

ENV GOPATH=/go
ENV PATH=${GOPATH}/bin:/usr/local/go/bin:$PATH

RUN mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 777 "$GOPATH"

WORKDIR /usr/local/libtraceable-downloader

COPY . .

RUN go get ./...

RUN go install github.com/Traceableai/goagent/filters/traceable/cmd/libtraceable-downloader

RUN $(go env GOPATH)/bin/libtraceable-downloader pull-library /usr/local/traceable