ARG DEBIAN_VERSION

FROM debian:${DEBIAN_VERSION}

RUN apt-get -qq update && apt-get -qq install -y wget git gcc

ARG GO_VERSION

RUN wget https://dl.google.com/go/go${GO_VERSION}.linux-amd64.tar.gz && \
    tar -xvf go${GO_VERSION}.linux-amd64.tar.gz && \
    mv go /usr/local

ENV GOROOT=/usr/local/go
ENV PATH=$GOPATH/bin:$GOROOT/bin:$PATH

WORKDIR /usr/local/libtraceable-downloader

COPY . .

RUN go get ./...

RUN go install github.com/Traceableai/goagent/filters/blocking/cmd/libtraceable-downloader

RUN $(go env GOPATH)/bin/libtraceable-downloader pull-library ./lib