ARG AMAZONLINUX_VERSION

FROM amazonlinux:${AMAZONLINUX_VERSION}

RUN yum -y update && yum install -y wget gcc tar gzip

ARG GO_VERSION

RUN wget https://dl.google.com/go/go${GO_VERSION}.linux-amd64.tar.gz && \
    tar -xvf go${GO_VERSION}.linux-amd64.tar.gz && \
    mv go /usr/local

ENV GOROOT=/usr/local/go
ENV PATH=$GOPATH/bin:$GOROOT/bin:$PATH

WORKDIR /usr/local/libtraceable-downloader

COPY . .

RUN go get ./...

RUN go install github.com/Traceableai/goagent/filters/blocking/cmd/libtraceable-downloader

RUN $(go env GOPATH)/bin/libtraceable-downloader pull-library /etc/traceable